#!/bin/bash

## this file is used to start xampp
##to usr/bin
##if [ $1 == "0" ]
#then 
#	sudo /opt/lampp/xampp stop;
#	exit;
#fi
#sudo /opt/lampp/xampp start;
st=($(sudo /opt/lampp/xampp status | grep running | tr '.' "\n"))
echo -e ${st[0]};
